version: "3.7"
services:
  qp_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql:mysqldb:3306/grocery
    depends_on:
      - mysqldb
    networks:
      - spring-qa

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - spring-qa
networks:
    spring-qa:
